services:
  postgres_database:
    image: postgres
    container_name: ignite-ps-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=ignite
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app
    
volumes:
  pgdata: 
    driver: local